services:
  db:
    restart: unless-stopped
    image: "mariadb:10.6.9"
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "laser-arena-control"
      MARIADB_ROOT_PASSWORD: "laser-arena-control"
      MYSQL_DATABASE: "lac"
      MARIADB_DATABASE: "lac"
    volumes:
      - mariadb-liga-dev:/var/lib/mysql
    networks:
      - backend
  redis:
    restart: unless-stopped
    image: eqalpha/keydb:latest
    ports:
      - "6378:6379"
    networks:
      - backend
      - frontend
    volumes:
      - ./docker/redis/data:/data
  php:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    working_dir: /var/www/
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    volumes:
      - ./:/var/www
      - ./docker/fpm/:/etc/php/
      - ./docker/core/php.ini:/usr/local/etc/php/php.ini
    networks:
      - backend
    environment:
      APP_NAME: "Laser liga"
      DB_HOST: "db"
      DB_PORT: 3306
      DB_DATABASE: "lac"
      DB_USER: "root"
      DB_PASSWORD: "laser-arena-control"
  web:
    restart: unless-stopped
    image: nginx:alpine
    depends_on:
      - php
      - db
    ports:
      - "8002:80"
    networks:
      - backend
      - frontend
    links:
      - php
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx
volumes:
  mariadb-liga-dev:
networks:
  backend:
  frontend: